/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * pSerie.java
 *
 * Created on 18-ene-2014, 21:13:44
 */

package Series;

import javax.swing.JComboBox;

/**
 *
 * @author July
 */
public class pSerie extends javax.swing.JPanel {

    /** Creates new form pSerie */
    public pSerie() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTitulo = new javax.swing.JLabel();
        jTemporada = new javax.swing.JLabel();
        jCapitulo = new javax.swing.JLabel();
        jNombre = new javax.swing.JTextField();
        comboTemp = new javax.swing.JComboBox();
        comboCap = new javax.swing.JComboBox();
        jTitular = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        jTitulo.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTitulo.setForeground(new java.awt.Color(255, 102, 0));
        jTitulo.setText("Titulo:");

        jTemporada.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTemporada.setForeground(new java.awt.Color(255, 102, 0));
        jTemporada.setText("Temporada:");

        jCapitulo.setFont(new java.awt.Font("Tahoma", 1, 11));
        jCapitulo.setForeground(new java.awt.Color(255, 102, 0));
        jCapitulo.setText("Capítulo:");

        jNombre.setForeground(new java.awt.Color(255, 102, 0));

        comboTemp.setBackground(new java.awt.Color(0, 0, 0));
        comboTemp.setForeground(new java.awt.Color(255, 102, 0));
        comboTemp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        comboCap.setBackground(new java.awt.Color(0, 0, 0));
        comboCap.setForeground(new java.awt.Color(255, 102, 0));
        comboCap.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100" }));

        jTitular.setFont(new java.awt.Font("Tahoma", 1, 24));
        jTitular.setForeground(new java.awt.Color(255, 153, 0));
        jTitular.setText("INTRODUCE UNA NUEVA SERIE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTitulo)
                    .addComponent(jTemporada)
                    .addComponent(jCapitulo))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(54, 54, 54))
                        .addComponent(comboTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(jTitular)
                .addGap(123, 123, 123))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTitular)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTitulo))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTemporada)
                    .addComponent(comboTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCapitulo)
                    .addComponent(comboCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public String getTitulo(){
        return jNombre.getText();
    }

    public void setTitulo(String titulo){
        jNombre.setText(titulo);
    }

    public int getTemp(){
        int temp= Integer.parseInt((String)comboTemp.getSelectedItem());
        return temp;
    }

    public int getCap(){
        int cap= Integer.parseInt((String)comboCap.getSelectedItem());
        return cap;
    }
    
    public JComboBox getcomboTemp(){
        return comboTemp;
    }

    public JComboBox getcomboCap(){
        return comboCap;
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboCap;
    private javax.swing.JComboBox comboTemp;
    private javax.swing.JLabel jCapitulo;
    private javax.swing.JTextField jNombre;
    private javax.swing.JLabel jTemporada;
    private javax.swing.JLabel jTitular;
    private javax.swing.JLabel jTitulo;
    // End of variables declaration//GEN-END:variables

}
